services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - localSTORAGE:/usr/app
      - /usr/app/node_modules
      
volumes:
  localSTORAGE: