import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NaveBar from "@/components/admin/NaveBar";
import SideBar from "@/components/admin/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-svh`}
      >
        <div className="relative w-full h-full">
            <NaveBar/>
            <SideBar/>
            <div className='w-full h-full pt-[55px] pl-[80px] md:pl-[130px]'>
                {children}
            </div>
        </div>
      </body>
    </html>
  );
}
