import PaginationComponent from '@/components/paginate/Paginate'
import React from 'react'

interface payedUser{
  id:string;
  userName:string;
  invoice:number;
  receved:number;
  methord:string;
  branch:string;
  date:string;
  remark:string;
}

const getPayment:payedUser[] = [
  {
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },{
    invoice:23,
    id:"lskd",
    userName:"kdkal",
    receved:2000,
    methord:"Bkash",
    branch:"Jarayangonj",
    date:"10-02-2024",
    remark:"Sakib"
  },
]

const page = () => {
  return (
    <div>
      <section className='w-full max-w-[1600px] p-6 mx-auto'>
        <PaginationComponent<payedUser>
          addUserButton={false}
          paginateTitle='Live Connection report'
          // add a get paymet resite layter
          action={{view:true,delete:true}}
          fields={["Invoice","ID","UserName","Received","Transaction","Branch","Data","Remark"]}
          allData={getPayment}
        />
      </section>
    </div>
  )
}

export default page